services:
    ysocode.test:
        build:
            context: ./vendor/ysocode/peach/runtimes/frankenphp/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: peach-8.3/frankenphp
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '80:80'
            - '443:443'
            - '443:443/udp'
        environment:
            WWWUSER: '${WWWUSER}'
            XDEBUG_MODE: '${PEACH_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${PEACH_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            FRANKENPHP_CONFIG: '${FRANKENPHP_CONFIG}'
        volumes:
            - './:/app/public'
            - 'caddy_data:/data'
            - 'caddy_config:/config'
        tty: true
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'peach-mysql:/var/lib/mysql'
            - './vendor/ysocode/peach/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - peach
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
volumes:
    caddy_data: null
    caddy_config: null
    peach-mysql:
        driver: local
networks:
    peach:
        driver: bridge
