#!/bin/sh
set -e

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER peach
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
        set -- frankenphp run "$@"
fi

exec "$@"